# Generated by Django 6.0.1 on 2026-03-31 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_project_area_remove_project_duration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectsettings',
            name='ai_risk_trends_enabled',
            field=models.BooleanField(default=True, help_text='Enable AI-powered risk trend predictions'),
        ),
        migrations.AddField(
            model_name='projectsettings',
            name='equipment_count',
            field=models.IntegerField(default=0, help_text='Number of equipment items'),
        ),
        migrations.AddField(
            model_name='projectsettings',
            name='man_hours',
            field=models.IntegerField(default=0, help_text='Total man-hours worked'),
        ),
        migrations.AddField(
            model_name='projectsettings',
            name='openai_api_key',
            field=models.CharField(blank=True, default='', help_text='OpenAI API key for AI analysis', max_length=500),
        ),
    ]
